### ISSUE TITLE
Change color scheme a bit in code sample for component "BlogContent"?

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/react-hooks-props-basics#2]
### Canvas Link

https://learning.flatironschool.com/courses/5186/assignments/180040?module_item_id=397461

### Concern

I like the color in the examples provided. But can we tweak it to show the invoked component (BlogContent) in a different color from the props attribute it's setting up? i.e. both pieces are green in the attached slide, so the difference doesn't doesn't stand out as much as we see of this same info in VS Code. Sounds like no big deal, but I was wandering around a while (!!!) before finally noticing that the referenced component was really in the sample. Contrasting color would have helped me make the connection faster and keep moving along.

<img width="533" alt="Screen Shot 2022-05-19 at 8 29 27 PM" src="https://user-images.githubusercontent.com/10212911/169426873-f0d93872-9a07-4b3a-9353-0f03e681bd25.png">

### Suggested Changes

The samples are good. The content is there. Still, enhancing the color contrast regarding identifier types might make it that much easier for students to identify what's there. I might have found what I was seeking sooner if a different color scheme such as from VS Code. Perhaps such changes would be needed throughout the material for consistent styling, and be too much to take on, but I can at least let you know where I had an issue.
![Screen Shot 2022-05-19 at 8 39 26 PM](https://user-images.githubusercontent.com/10212911/169426914-cc7a685e-7abd-41c9-9ef6-a5e39cacd624.png)

**Comment by lizbur10** [comment]
Hi @brigj1 - unfortunately, this is not an easy fix, due both to how custom CSS is created in Canvas and the fact that the courses in the other 3 Flatiron disciplines might be affected in an undesirable if when we change it. I will make a note of this suggestion for the next time we make updates.

**Comment by brigj1** [comment]
Yes, this one's not scalable.
Still, I thought you'd want to hear about such issues of me not cluing in
for a while. :-)
Thanks,
Brigham Johnson
